#!/usr/bin/env python3
"""
PDF Syllabus Generator for EduCraft
Generates professional PDF syllabi from JSON structure with RAG component expansion
"""

from datetime import datetime
from io import BytesIO

from fpdf import FPDF, XPos, YPos


def sanitize_text(text):
    """
    Sanitize text to be Latin-1 compatible for PDF generation
    Replaces common Unicode characters with ASCII equivalents
    """
    if not isinstance(text, str):
        return text

    replacements = {
        "\u2014": "--",
        "\u2013": "-",
        "\u2022": "-",
        "\u2019": "'",
        "\u2018": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u00a0": " ",
        "\u00bd": "1/2",
        "\u00bc": "1/4",
        "\u00be": "3/4",
    }

    for unicode_char, ascii_char in replacements.items():
        text = text.replace(unicode_char, ascii_char)

    try:
        text.encode("latin-1")
    except UnicodeEncodeError:
        text = text.encode("latin-1", errors="replace").decode("latin-1")

    return text


class SyllabusPDF(FPDF):
    """Professional PDF generator for educational syllabi"""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.set_margins(left=15, top=15, right=15)

    def header(self):
        """Page header with EduCraft branding"""
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, "EduCraft - AI-Powered Syllabus Generator", align="C")
            self.ln(12)

    def footer(self):
        """Page footer with page numbers"""
        if self.page_no() > 1:
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f"Page {self.page_no()-1}", align="C")

    def section_title(self, title, with_line=True):
        """Add formatted section title"""
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(31, 119, 180)
        self.cell(0, 10, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        if with_line:
            self.set_draw_color(31, 119, 180)
            self.set_line_width(0.5)
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())

        self.ln(8)

    def subsection_title(self, title):
        """Add formatted subsection title"""
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(2)

    def body_text(self, text, indent=0):
        """Add body text with optional indentation"""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(0, 0, 0)
        if indent > 0:
            self.set_x(self.l_margin + indent)
        self.multi_cell(0, 6, sanitize_text(text))
        self.ln(2)

    def create_cover_page(self, course_info, objectives):
        """Create cover page with course info and learning objectives"""
        self.add_page()
        self.ln(30)

        self.set_font("Helvetica", "B", 22)
        self.set_text_color(31, 119, 180)
        title = sanitize_text(course_info.get("title", "Course Syllabus"))
        self.multi_cell(0, 10, title, align="C")
        self.ln(8)

        self.set_font("Helvetica", "I", 10)
        self.set_text_color(120, 120, 120)
        self.cell(
            0,
            5,
            "Generated by EduCraft",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C",
        )
        self.ln(12)

        self.set_font("Helvetica", "B", 10)
        self.set_text_color(0, 0, 0)

        domain_display = course_info.get("domain", "N/A").replace("_", " ").title()
        level_display = course_info.get("level", "N/A").title()
        duration_display = course_info.get("duration", "N/A").title()

        details_line = f"{domain_display}  |  {level_display}  |  {duration_display}"
        self.cell(0, 6, details_line, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.ln(10)

        description = course_info.get("description", "")
        if description:
            self.set_font("Helvetica", "", 10)
            self.set_text_color(60, 60, 60)
            self.multi_cell(0, 5, sanitize_text(description), align="J")
            self.ln(8)

        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(10)

        self.set_font("Helvetica", "B", 14)
        self.set_text_color(31, 119, 180)
        self.cell(0, 8, "Learning Objectives", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(5)

        if objectives:
            self.set_font("Helvetica", "", 10)
            self.set_text_color(0, 0, 0)
            for i, obj in enumerate(objectives, 1):
                self.set_x(self.l_margin + 5)
                self.set_font("Helvetica", "B", 10)
                self.cell(8, 5, f"{i}.")
                self.set_font("Helvetica", "", 10)
                self.set_x(self.l_margin + 13)
                self.multi_cell(0, 5, sanitize_text(obj))
                self.ln(2)
        else:
            self.set_font("Helvetica", "I", 10)
            self.set_text_color(128, 128, 128)
            self.cell(0, 6, "No learning objectives specified")

        self.ln(10)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        timestamp = datetime.now().strftime("%B %d, %Y at %H:%M")
        self.cell(
            0,
            5,
            f"Generated on {timestamp}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C",
        )

    def add_modules_section(self, module_uuids, rag_database):
        """Add modules section with full details from RAG database"""
        self.add_page()
        self.section_title("Course Modules")

        if not module_uuids:
            self.set_font("Helvetica", "I", 10)
            self.set_text_color(128, 128, 128)
            self.cell(0, 8, "No modules selected")
            return

        uuid_to_module = {}
        if rag_database:
            uuid_to_module = {m["id"]: m for m in rag_database.get("modules", [])}

        for i, module_uuid in enumerate(module_uuids, 1):
            module = uuid_to_module.get(module_uuid)

            if not module:
                self.subsection_title(f"Module {i}")
                self.set_font("Helvetica", "I", 9)
                self.set_text_color(128, 128, 128)
                self.cell(0, 6, f"Module details not available (UUID: {module_uuid})")
                self.ln(8)
                continue

            self.set_font("Helvetica", "B", 13)
            self.set_text_color(31, 119, 180)
            module_title = sanitize_text(
                f"Module {i}: {module.get('title', 'Untitled')}"
            )
            self.multi_cell(0, 7, module_title)
            self.ln(2)

            self.set_font("Helvetica", "I", 9)
            self.set_text_color(100, 100, 100)
            hours = module.get("estimated_hours", 0)
            difficulty = module.get("difficulty", "N/A").title()
            self.set_x(self.l_margin)
            self.multi_cell(0, 5, f"{hours} hours  |  {difficulty}")
            self.ln(3)

            description = module.get("description", "")
            if description:
                self.set_font("Helvetica", "", 9)
                self.set_text_color(0, 0, 0)
                self.multi_cell(0, 5, sanitize_text(description), align="J")
                self.ln(3)

            key_concepts = module.get("key_concepts", [])
            if key_concepts:
                self.set_font("Helvetica", "B", 9)
                self.set_text_color(0, 0, 0)
                self.cell(0, 5, "Key Concepts:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                self.ln(1)

                self.set_font("Helvetica", "", 9)
                for concept in key_concepts[:5]:
                    self.set_x(self.l_margin + 5)
                    self.cell(3, 5, "-")
                    self.set_x(self.l_margin + 10)
                    self.multi_cell(0, 5, sanitize_text(concept))
                self.ln(2)

            if i < len(module_uuids):
                self.set_draw_color(200, 200, 200)
                self.set_line_width(0.2)
                self.line(
                    self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y()
                )
                self.ln(6)

    def add_activities_section(self, activity_uuids, rag_database):
        """Add learning activities section flowing from previous content"""
        self.ln(12)
        self.section_title("Learning Activities")

        if not activity_uuids:
            self.set_font("Helvetica", "I", 10)
            self.set_text_color(128, 128, 128)
            self.cell(0, 8, "No activities selected")
            return

        uuid_to_activity = {}
        if rag_database:
            uuid_to_activity = {a["id"]: a for a in rag_database.get("activities", [])}

        for i, activity_uuid in enumerate(activity_uuids, 1):
            activity = uuid_to_activity.get(activity_uuid)

            if not activity:
                self.set_font("Helvetica", "I", 9)
                self.set_text_color(128, 128, 128)
                self.cell(0, 6, f"{i}. Activity details not available")
                self.ln(6)
                continue

            self.set_font("Helvetica", "B", 11)
            self.set_text_color(0, 0, 0)
            title = sanitize_text(f"{i}. {activity.get('title', 'Untitled')}")
            self.multi_cell(0, 6, title)

            self.set_font("Helvetica", "I", 8)
            self.set_text_color(100, 100, 100)
            bloom = activity.get("bloom_level", "N/A").title()
            hours = activity.get("estimated_hours", 0)
            self.set_x(self.l_margin)
            self.multi_cell(0, 5, f"Bloom's Level: {bloom}  |  {hours} hours")
            self.ln(2)

            description = activity.get("description", "")
            if description:
                self.set_font("Helvetica", "", 9)
                self.set_text_color(0, 0, 0)
                self.set_x(self.l_margin + 5)
                self.multi_cell(0, 5, sanitize_text(description))

            self.ln(4)

    def add_assessments_section(self, assessment_uuids, rag_database):
        """Add assessments section flowing from previous content"""
        self.ln(12)
        self.section_title("Assessments")

        if not assessment_uuids:
            self.set_font("Helvetica", "I", 10)
            self.set_text_color(128, 128, 128)
            self.cell(0, 8, "No assessments selected")
            return

        uuid_to_assessment = {}
        if rag_database:
            uuid_to_assessment = {
                a["id"]: a for a in rag_database.get("assessments", [])
            }

        for i, assessment_uuid in enumerate(assessment_uuids, 1):
            assessment = uuid_to_assessment.get(assessment_uuid)

            if not assessment:
                self.set_font("Helvetica", "I", 9)
                self.set_text_color(128, 128, 128)
                self.cell(0, 6, f"{i}. Assessment details not available")
                self.ln(6)
                continue

            self.set_font("Helvetica", "B", 11)
            self.set_text_color(0, 0, 0)
            title = sanitize_text(f"{i}. {assessment.get('title', 'Untitled')}")
            self.multi_cell(0, 6, title)

            self.set_font("Helvetica", "I", 8)
            self.set_text_color(100, 100, 100)
            assessment_type = assessment.get("assessment_type", "N/A").title()
            hours = assessment.get("estimated_hours", 0)
            self.set_x(self.l_margin)
            self.multi_cell(
                0, 5, f"Type: {assessment_type}  |  Duration: {hours} hours"
            )
            self.ln(2)

            description = assessment.get("description", "")
            if description:
                self.set_font("Helvetica", "", 9)
                self.set_text_color(0, 0, 0)
                self.set_x(self.l_margin + 5)
                self.multi_cell(0, 5, sanitize_text(description))

            self.ln(4)


def generate_syllabus_pdf(syllabus_json, rag_database=None):
    """
    Generate complete PDF from syllabus JSON with RAG database expansion

    Args:
        syllabus_json: Dictionary containing syllabus structure
        rag_database: Optional RAG database for component expansion

    Returns:
        BytesIO buffer containing PDF data
    """
    pdf = SyllabusPDF()

    course_info = syllabus_json.get("course_info", {})
    objectives = syllabus_json.get("learning_objectives", [])
    modules = syllabus_json.get("modules", [])
    activities = syllabus_json.get("activities", [])
    assessments = syllabus_json.get("assessments", [])

    pdf.create_cover_page(course_info, objectives)
    pdf.add_modules_section(modules, rag_database)
    pdf.add_activities_section(activities, rag_database)
    pdf.add_assessments_section(assessments, rag_database)

    pdf_buffer = BytesIO()
    pdf_bytes = pdf.output()
    pdf_buffer.write(pdf_bytes)
    pdf_buffer.seek(0)

    return pdf_buffer


if __name__ == "__main__":
    # Test with expanded sample data
    import json
    from pathlib import Path

    print("Testing PDF generator with sample data...")

    sample_syllabus = {
        "course_info": {
            "title": "Introduction to Python Programming",
            "domain": "computer_science",
            "level": "beginner",
            "duration": "semester",
            "description": "Foundational programming concepts using Python, including variables, data types, control flow (conditionals and loops), functions, lists, dictionaries, string manipulation, file I/O, and error handling.",
        },
        "learning_objectives": [
            "Students will write Python programs using variables, data types, and operators to solve basic computational problems",
            "Students will implement control flow structures (if/else, loops) to create programs with decision-making and repetition",
            "Students will define and use functions to organize code into reusable, modular components",
        ],
        "modules": ["38386727-086d-47e7-873b-465566f4067d"],  # EDA module from data
        "activities": [],
        "assessments": [],
    }

    # Load RAG database
    base_dir = Path(__file__).parent.parent
    components_dir = base_dir / "data" / "components"

    rag_database = {}
    if (components_dir / "modules.json").exists():
        with open(components_dir / "modules.json") as f:
            rag_database["modules"] = json.load(f)

    if (components_dir / "activities.json").exists():
        with open(components_dir / "activities.json") as f:
            rag_database["activities"] = json.load(f)

    if (components_dir / "assessments.json").exists():
        with open(components_dir / "assessments.json") as f:
            rag_database["assessments"] = json.load(f)

    pdf_buffer = generate_syllabus_pdf(sample_syllabus, rag_database)

    # Save to file
    output_path = "syllabus_full.pdf"
    with open(output_path, "wb") as f:
        f.write(pdf_buffer.getvalue())

    print(f"✅ PDF generated successfully: {output_path}")
    print(f"   File size: {len(pdf_buffer.getvalue())} bytes")
