#!/usr/bin/env python3
"""
Proof-of-Concept: PDF Syllabus Generator
Simple demonstration of cover page + one section using FPDF2
"""

from datetime import datetime
from io import BytesIO

from fpdf import FPDF, XPos, YPos


class SyllabusPDFPOC(FPDF):
    """Proof-of-concept PDF generator for educational syllabi"""

    def header(self):
        """Page header with EduCraft branding"""
        if self.page_no() > 1:  # Skip header on cover page
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, "EduCraft - AI-Powered Syllabus Generator", align="C")
            self.ln(15)

    def footer(self):
        """Page footer with page numbers"""
        if self.page_no() > 1:  # Skip footer on cover page
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f"Page {self.page_no()-1}", align="C")

    def create_cover_page(self, course_info, objectives):
        """Create cover page with course info and learning objectives"""
        self.add_page()
        self.ln(30)

        # Main title
        self.set_font("Helvetica", "B", 22)
        self.set_text_color(31, 119, 180)
        self.multi_cell(0, 10, course_info.get("title", "Course Syllabus"), align="C")
        self.ln(8)

        # EduCraft branding
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(120, 120, 120)
        self.cell(
            0,
            5,
            "Generated by EduCraft",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C",
        )
        self.ln(12)

        # Course details (compact, inline)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(0, 0, 0)

        domain_display = course_info.get("domain", "N/A").replace("_", " ").title()
        level_display = course_info.get("level", "N/A").title()
        duration_display = course_info.get("duration", "N/A").title()

        details_line = f"{domain_display}  |  {level_display}  |  {duration_display}"
        self.cell(0, 6, details_line, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.ln(10)

        # Description
        description = course_info.get("description", "")
        if description:
            self.set_font("Helvetica", "", 10)
            self.set_text_color(60, 60, 60)
            self.multi_cell(0, 5, description, align="J")
            self.ln(8)

        # Horizontal separator
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(10)

        # Learning Objectives (on same page)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(31, 119, 180)
        self.cell(0, 8, "Learning Objectives", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(5)

        if objectives:
            self.set_font("Helvetica", "", 10)
            self.set_text_color(0, 0, 0)
            for i, obj in enumerate(objectives, 1):
                self.set_x(self.l_margin + 5)
                self.set_font("Helvetica", "B", 10)
                self.cell(8, 5, f"{i}.")
                self.set_font("Helvetica", "", 10)
                self.set_x(self.l_margin + 13)
                self.multi_cell(0, 5, obj)
                self.ln(2)
        else:
            self.set_font("Helvetica", "I", 10)
            self.set_text_color(128, 128, 128)
            self.cell(0, 6, "No learning objectives specified")

        # Generation timestamp at bottom
        self.ln(10)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        timestamp = datetime.now().strftime("%B %d, %Y at %H:%M")
        self.cell(
            0,
            5,
            f"Generated on {timestamp}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C",
        )


def generate_poc_pdf(syllabus_json):
    """
    Generate proof-of-concept PDF from syllabus JSON

    Args:
        syllabus_json: Dictionary containing syllabus data

    Returns:
        BytesIO buffer containing PDF data
    """
    pdf = SyllabusPDFPOC()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Extract course info and objectives
    course_info = syllabus_json.get("course_info", {})
    objectives = syllabus_json.get("learning_objectives", [])

    # Create cover page with objectives
    pdf.create_cover_page(course_info, objectives)

    # Output to BytesIO buffer (new API returns bytes directly)
    pdf_buffer = BytesIO()
    pdf_bytes = pdf.output()
    pdf_buffer.write(pdf_bytes)
    pdf_buffer.seek(0)

    return pdf_buffer


if __name__ == "__main__":
    # Test with sample data
    sample_syllabus = {
        "course_info": {
            "title": "Introduction to Python Programming",
            "domain": "computer_science",
            "level": "beginner",
            "duration": "semester",
            "description": "Foundational programming concepts using Python, including variables, data types, control flow (conditionals and loops), functions, lists, dictionaries, string manipulation, file I/O, and error handling.",
        },
        "learning_objectives": [
            "Students will write Python programs using variables, data types, and operators to solve basic computational problems",
            "Students will implement control flow structures (if/else, loops) to create programs with decision-making and repetition",
            "Students will define and use functions to organize code into reusable, modular components",
            "Students will manipulate data using lists, dictionaries, and strings to process information effectively",
            "Students will read from and write to files to persist data and handle basic I/O operations",
        ],
    }

    print("Generating proof-of-concept PDF...")
    pdf_buffer = generate_poc_pdf(sample_syllabus)

    # Save to file
    output_path = "syllabus_poc.pdf"
    with open(output_path, "wb") as f:
        f.write(pdf_buffer.getvalue())

    print(f"✅ PDF generated successfully: {output_path}")
    print(f"   File size: {len(pdf_buffer.getvalue())} bytes")
